name: tests-payments
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ticketing/payments/src/test
          touch setEnvVars.ts
          echo process.env.STRIPE_KEY='$STRIPE_KEY' >> setEnvVars.ts
          echo process.env.TEST_ENV='TEST' >> setEnvVars.ts
          
          cd ticketing/payments
          npm install
          npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
